Repository bu-ist/responsive-foundation, pull requests merged in 2018-12, with the labels that each got.

#186 Fixed widget button link color
  css-dev/burf-theme/widgets/_widgets.scss
  package-lock.json
Labels: bug

#187 Feature/reduce dependencies fixes
  CHANGELOG.md
  Gruntfile.js
  css-dev/burf-base.scss
  css-dev/burf-base/icons/_package.scss
  css-dev/burf-theme.scss
  css-dev/burf-tools/_tools-grunt.scss
  package-lock.json
  package.json
Labels: bug

#188 Feature/print styles
  css-dev/burf-base.scss
  css-dev/burf-base/_mixins.scss
  css-dev/burf-base/_print.scss
  css-dev/burf-theme/layout/_footer.scss
Labels: enhancement, sass

#189 Generate icon classes from map instead of manual mixin calls
  CHANGELOG.md
  css-dev/burf-base/icons/_actions.scss
  css-dev/burf-base/icons/_arrows.scss
  css-dev/burf-base/icons/_charts.scss
  css-dev/burf-base/icons/_communication.scss
  css-dev/burf-base/icons/_documents.scss
  css-dev/burf-base/icons/_ecommerce.scss
  css-dev/burf-base/icons/_editing.scss
  css-dev/burf-base/icons/_location.scss
  css-dev/burf-base/icons/_media.scss
  css-dev/burf-base/icons/_mixins.scss
  css-dev/burf-base/icons/_objects.scss
  css-dev/burf-base/icons/_package.scss
  css-dev/burf-base/icons/_social.scss
  css-dev/burf-base/icons/_status.scss
  css-dev/burf-base/icons/_technology.scss
  css-dev/burf-base/icons/_time.scss
  css-dev/burf-base/icons/_transportation.scss
  css-dev/burf-base/icons/_ui.scss
Labels: Ready to Ship
