Repository bu-ist/responsive-foundation, pull requests merged in 2019-01, with the labels that each got.

#185 Mega Navigation
  CHANGELOG.md
  css-dev/burf-base/icons/_mixins.scss
  css-dev/burf-theme/layout/_navigation.scss
Labels: In Progress

#191 Feature/es6 support
  .babelrc
  .codeclimate.yml
  .eslintrc.json
  .sasslintrc
  Gruntfile.js
  _docs/css-dev/docs.scss
  css-dev/burf-base/icons/_package.scss
  js-dev/modules/toggle.js
  js-dev/theme.js
  js-dev/toggle.js
  js/theme.js
  js/theme.js.map
  package-lock.json
  package.json
Labels: enhancement

#197 Update tools-cgb with new icons implementation
  css-dev/burf-tools/_tools-cgb.scss
Labels: bug
